#spring生成环境
spring:
  profiles:
    active: dev

#redis配置
  redis:
    database: 1
    port: 6379
    password: 
    pool:
      max-active: 1000
      max-wait: -1
      max-idle: 10
      min-idle: 2
    timeout: 0

#mybatis
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

#服务端口配置
server:
  port: 6666
  tomcat:
    uri-encoding: utf-8  


 
 
      